services:
#  db:
#    image: mariadb:10.3.39
#    container_name: mariadb
#    environment:
#      MYSQL_ROOT_PASSWORD: myrootpass
#      MYSQL_DATABASE: devdb
#      MYSQL_USER: devuser
#      MYSQL_PASSWORD: devpass
#    volumes:
#      - db-data:/var/lib/mysql

  web:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    container_name: web
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

