services:
  web:
    build:
      context: ../..
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    container_name: web
    extra_hosts:
      - "host.docker.internal:host-gateway"

