"""first commit

Revision ID: 159100757125
Revises: 
Create Date: 2025-09-06 11:29:09.696656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159100757125'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='고유 PK'),
    sa.Column('status', sa.String(length=200), nullable=False, comment='상태'),
    sa.Column('message', sa.String(length=200), nullable=False, comment='메시지'),
    sa.Column('data', sa.String(length=200), nullable=False, comment='데이터'),
    sa.Column('username', sa.String(length=200), nullable=False, comment='사용자ID'),
    sa.Column('trace_id', sa.String(length=100), nullable=False, comment='트레이스 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.PrimaryKeyConstraint('id'),
    comment='로그 정보',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='고유 PK'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='아이디'),
    sa.Column('password', sa.String(length=200), nullable=False, comment='비밀번호'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.Column('is_deleted', sa.String(length=1), server_default=sa.text("'F'"), nullable=True, comment='삭제 여부'),
    sa.PrimaryKeyConstraint('id'),
    comment='회원 기본정보',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_t_user_username'), 't_user', ['username'], unique=True)
    op.create_table('t_user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='고유 PK'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='t_user 고유 PK'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='닉네임'),
    sa.Column('fullname', sa.String(length=100), nullable=True, comment='이름'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='생년월일'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='휴대폰'),
    sa.Column('telephone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('zipcode', sa.String(length=10), nullable=True, comment='우편번호'),
    sa.Column('address1', sa.String(length=200), nullable=True, comment='주소'),
    sa.Column('address2', sa.String(length=200), nullable=True, comment='상세주소'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='이메일'),
    sa.Column('email_consent', sa.String(length=1), server_default=sa.text("'F'"), nullable=True, comment='이메일 수신'),
    sa.Column('sms_consent', sa.String(length=1), server_default=sa.text("'F'"), nullable=True, comment='SMS 수신'),
    sa.Column('referrer_username', sa.String(length=50), nullable=True, comment='추천인 아이디'),
    sa.Column('company_name', sa.String(length=50), nullable=True, comment='업체명'),
    sa.Column('ceo_name', sa.String(length=50), nullable=True, comment='대표자명'),
    sa.Column('company_tel', sa.String(length=50), nullable=True, comment='업체전화번호'),
    sa.Column('business_type', sa.String(length=50), nullable=True, comment='업태'),
    sa.Column('business_item', sa.String(length=50), nullable=True, comment='업종'),
    sa.Column('company_zipcode', sa.String(length=50), nullable=True, comment='업체 우편번호'),
    sa.Column('company_address1', sa.String(length=50), nullable=True, comment='업체 주소'),
    sa.Column('company_address2', sa.String(length=50), nullable=True, comment='업체 상세주소'),
    sa.Column('business_number', sa.String(length=50), nullable=True, comment='사업자번호'),
    sa.Column('business_license', sa.String(length=50), nullable=True, comment='사업자등록증'),
    sa.Column('power_of_attorney', sa.String(length=50), nullable=True, comment='위임장'),
    sa.Column('last_login_at', sa.String(length=50), nullable=True, comment='마지막 접속일시'),
    sa.Column('pobox_code', sa.String(length=50), nullable=True, comment='사서함 번호'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.Column('is_deleted', sa.String(length=1), server_default=sa.text("'F'"), nullable=True, comment='삭제 여부'),
    sa.PrimaryKeyConstraint('id'),
    comment='회원 추가정보',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_t_user_info_user_id'), 't_user_info', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_info_user_id'), table_name='t_user_info')
    op.drop_table('t_user_info')
    op.drop_index(op.f('ix_t_user_username'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_table('t_logs')
    # ### end Alembic commands ###
