"""create logs table

Revision ID: b2bcda059993
Revises: c5cfbcc887e9
Create Date: 2025-09-06 11:03:26.882181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2bcda059993'
down_revision: Union[str, None] = 'c5cfbcc887e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='고유 PK'),
    sa.Column('status', sa.String(length=200), nullable=False, comment='상태'),
    sa.Column('message', sa.String(length=200), nullable=False, comment='메시지'),
    sa.Column('data', sa.String(length=200), nullable=False, comment='데이터'),
    sa.Column('username', sa.String(length=200), nullable=False, comment='사용자ID'),
    sa.Column('trace_id', sa.String(length=100), nullable=False, comment='트레이스 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.PrimaryKeyConstraint('id'),
    comment='로그 정보',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_logs')
    # ### end Alembic commands ###
