"""update

Revision ID: bc938af20f83
Revises: 159100757125
Create Date: 2025-09-06 17:32:57.495872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc938af20f83'
down_revision: Union[str, None] = '159100757125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('user_type', sa.String(length=20), server_default='b2b', nullable=False, comment='회원 유형 (admin/b2b/b2c)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'user_type')
    # ### end Alembic commands ###
